# Generated by Django 5.2.6 on 2025-10-08 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('reach', models.IntegerField(blank=True, null=True)),
                ('stance', models.CharField(blank=True, max_length=20)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=50)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouts', to='ufc_app.event')),
                ('fighter_blue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouts_blue', to='ufc_app.fighter')),
                ('fighter_red', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouts_red', to='ufc_app.fighter')),
            ],
        ),
        migrations.AddField(
            model_name='fighter',
            name='weight_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fighters', to='ufc_app.weightclass'),
        ),
    ]
